# Generated by Django 2.1.1 on 2018-10-17 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produk', '0002_auto_20180914_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=15, null=True)),
                ('alamat', models.TextField()),
                ('ongkir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('checkout', 'Checkout'), ('paid', 'Terbayar'), ('delivered', 'Terkirim')], default='checkout', max_length=10)),
                ('totalbelanja', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty', models.IntegerField(default=1)),
                ('totalhargabarang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Order')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk')),
            ],
        ),
    ]
